### ISSUE TITLE
pbboot刷入后反复重启无法启动

### ISSUE THREAD

**Issue by jhsb** [XFY9326/Xiaomi-R3-OpenWrt-Stable#2]
pbboot刷入后反复重启无法启动

因无法进入web或者ssh，无法提供日志

**Comment by XFY9326** [comment]
或许能提供一下你的操作步骤，这会有助于解决问题

**Comment by jhsb** [comment]
我在官方固件中开启ssh 刷入pbboot的bootloader，然后按reset开机进入pbboot网页上传pbboot的刷机固件。刷完不开机，反复重启，三个网口灯一直反复长亮，正面亮黄灯，插入lan口提示获取不到ip地址，反复在网线已拔出与正在获取ip地址中跳跃。发自我的iPhone------------------ 原始邮件 ------------------发件人: 逸雪飞扬  ***@***.***>发送时间: 2021年11月23日 19:04收件人: XFY9326/Xiaomi-R3-OpenWrt-Stable ***@***.***>抄送: jhsb ***@***.***>, Author ***@***.***>主题: Re: [XFY9326/Xiaomi-R3-OpenWrt-Stable] pbboot刷入后反复重启无法启动 (Issue #2)
或许能提供一下你的操作步骤，这会有助于解决问题

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/XFY9326/Xiaomi-R3-OpenWrt-Stable/issues/2#issuecomment-976405095",
"url": "https://github.com/XFY9326/Xiaomi-R3-OpenWrt-Stable/issues/2#issuecomment-976405095",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by XFY9326** [comment]
我觉得应该是启动时遇到了问题反复重启了，我之前也是按照这个步骤安装release里面的固件，但是没有遇到任何问题。抱歉，目前机器也出手给别人了，也无法进一步调试了。或许你可以尝试一下X-wrt，因为本身适配源码来自于那里。具体需要搬运修改的文件可以看patch里的操作，或许需要手动修改一下。

**Comment by jhsb** [comment]
感谢解答，我尝试ssh手动刷入rootfs0和kernel1可正常启动没问题，也许是pbboot固件打包的问题发自我的iPhone------------------ 原始邮件 ------------------
我觉得应该是启动时遇到了问题反复重启了，我之前也是按照这个步骤安装release里面的固件，但是没有遇到任何问题。抱歉，目前机器也出手给别人了，也无法进一步调试了。或许你可以尝试一下X-wrt，因为本身适配源码来自于那里。具体需要搬运修改的文件可以看patch里的操作，或许需要手动修改一下。
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/XFY9326/Xiaomi-R3-OpenWrt-Stable/issues/2#issuecomment-985582066",
"url": "https://github.com/XFY9326/Xiaomi-R3-OpenWrt-Stable/issues/2#issuecomment-985582066",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by XFY9326** [comment]
关于构建pbboot固件这块我是看其他大佬的分区解析实现的，所以会不会有其他分区变化我也不是很清楚。
