### ISSUE TITLE
编译的bp-boot格式的bin文件，在pb-boot的网页上烧录进去后，小米路由器无线重启

### ISSUE THREAD

**Issue by MortalM** [XFY9326/Xiaomi-R3-OpenWrt-Stable#3]
大佬好，我想请问下，我的设备是小米路由器3，用最新的lean源码编译，并且更改了target/linux/ramips/image/mt7620.mk文件，使编译可以生成pb-boot.bin的sysupgrade安装文件，然后在192.168.1.1的pb-boot中刷这个包，路由器会不断重启，我刷x-wrt和大佬您的固件却可以正常启动，我想自己编译，请问是我有哪里还需要更改吗， 这个问题困扰我半个月了。希望大佬可以解惑，谢谢
这是我 /lede/target/linux/ramips/image/mt7620.mk文件的配置，是还需要改其他的吗。
define Device/xiaomi_miwifi-r3
  SOC := mt7620a
  BLOCKSIZE := 128k
  PAGESIZE := 2048
  KERNEL_SIZE := 4096k
  IMAGE_SIZE := 32768k
  UBINIZE_OPTS := -E 5
  IMAGES += kernel1.bin rootfs0.bin pb-boot.bin
  IMAGE/kernel1.bin := append-kernel | check-size $$$$(KERNEL_SIZE)
  IMAGE/rootfs0.bin := append-ubi | check-size $$$$(IMAGE_SIZE)
  IMAGE/sysupgrade.bin := sysupgrade-tar | append-metadata
  IMAGE/pb-boot.bin := append-kernel | pad-to $$(KERNEL_SIZE) | \
                             append-kernel | pad-to $$(KERNEL_SIZE) | \
                             append-ubi | check-size $$$$(IMAGE_SIZE)
  DEVICE_VENDOR := Xiaomi
  DEVICE_MODEL := Mi Router R3
  DEVICE_PACKAGES := kmod-mt76x2 kmod-usb2 kmod-usb-ohci uboot-envtools
endef
TARGET_DEVICES += xiaomi_miwifi-r3

**Comment by XFY9326** [comment]
我并没有通过修改这里的参数生成pbboot需要的包，而是直接通过命令对kernel1.bin与rootfs0.bin进行合并操作。之前也试过在这里加，但是由于我的理解不足也是没法用（现在怀疑可能和“tr "\000" "\377"”有关）。具体合并的命令可以查看.github/workflows/build-openwrt.yml中的Build PbBoot firmware这一块的代码。
