### ISSUE TITLE
WiFi 2.4 / 5 GHz drops randomly

### ISSUE THREAD

**Issue by gitnewcomer** [XFY9326/Xiaomi-R3-OpenWrt-Stable#4]
Hi, could you build the last snapshot version of OpenWRT with the changes for Xiaomi Router R3?
It seems that this problem is solved on new snapshots and kernel like seen on this comment: https://github.com/openwrt/mt76/issues/551#issuecomment-1024378594
Thanks!

**Comment by XFY9326** [comment]
Sorry, my Xiaomi router device has already been sold, so I can no longer test it. But you can understand which files need to be changed by reading my patch file. I think it is mainly the upgrade of the kernel version from 5.4 to 5.10 that requires new adaptations. You can find the relevant adaptation code in the [X-Wrt project](https://github.com/x-wrt/x-wrt).  
Here is the patch file list for kernel 5.4.  
```
/package/boot/uboot-envtools/files/ramips
/target/linux/ramips/dts/mt7620a_xiaomi_miwifi-r3.dts
/target/linux/ramips/image/mt7620.mk
/target/linux/ramips/mt7620/base-files/etc/board.d/02_network
/target/linux/ramips/mt7620/base-files/lib/upgrade/platform.sh
/target/linux/ramips/mt7620/config-5.4
/target/linux/ramips/mt7620/target.mk
/target/linux/ramips/patches-5.4/0038-mtd-ralink-add-mt7620-nand-driver.patch
```
